name: MLOps on Jupyter for KSC example

on: workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Set up ML stacks and tools
      run: |
          pip install ethos_u_vela
          pip install tensorflow
          pip install tensorflow_datasets
          sudo apt-get install -y xxd
    - uses: yaananth/run-notebook@v2
      env:
        RUNNER: ${{ toJson(runner) }}
        SECRETS: ${{ toJson(secrets) }}
        GITHUB: ${{ toJson(github) }}
      with:
        notebook: "${{ github.workspace }}/ethos-u-ksc/train_and_deploy.ipynb"
        isReport: False
        poll: True
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: output
        path: ${{ RUNNER.temp }}/nb-runner
      env:
        RUNNER: ${{ toJson(runner) }}
